### ISSUE TITLE
fix string var names

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sugar-and-salt-solutions#22]
... that fail ESLint. See https://github.com/phetsims/chipper/issues/396#issuecomment-155566007.

**Comment by samreid** [comment]
@AshrafSharf please be apprised we have a new convention for string var names as identified in the link above, and the rule is being enforced by ESLint.  I'll commit fixes to sugar-and-salt-solutions shortly, but I just wanted to notify you.  Also, I pushed a fix to a file SugarAndSaltSharedProperties because it was causing launch failures.

**Comment by samreid** [comment]
Fixed above, reassigning to @AshrafSharf to review changes.

**Comment by veillette** [comment]
The simulation is passing lint. Closing
